main/urls.py
from django.urls import path
from main.views import show_main, create_product_flutter, create_product, create_ajax, edit_product, delete_product, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('create-ajax', create_ajax, name='create_ajax'),
    path('edit-product/<uuid:id>', edit_product, name='edit_product'),
    path('delete-product/<uuid:id>', delete_product, name='delete_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-flutter/', create_product_flutter, name='create_mood_flutter'),
]

marquette/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block meta %} {% endblock meta %}
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Satisfy&display=swap');
    </style>
    <link rel="stylesheet" href="{% static 'css/global.css' %}"/>
  </head>
  <body>
    {% block content %} {% endblock content %}
  </body>
</html>

templates/navbar.html
<nav class="fixed shadow-lg top-0 left-0 z-50 w-screen" style="background-color: #ecbad0;">
    <div class="max-w-8xl ms-auto px-4 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between h-16">
            <div class="flex items-center">
                <h1 class="text-3xl text-center text-black satisfy-regular">marquette</h1>
            </div>

            <div class="md:flex items-center hidden">
                <a href="#" class="text-center text-black font-bold px-5 py-2 mr-3">
                    Home
                </a>
                <a href="#" class="text-center text-black font-bold px-5 py-2 mr-3">
                    Products
                </a>
                {% if user.is_authenticated %}
                    <span class="text-black mr-4 font-bold">
                        Welcome, {{ user.username }}
                    </span>
                    <a href="{% url 'main:logout' %}" class="text-center text-white bg-[#c78ca0] hover:bg-[#d9a7a4] font-bold px-5 py-2 rounded transition duration-400">
                        Logout
                    </a>
                {% else %}
                    <a href="{% url 'main:login' %}" class="text-center text-white bg-[#c78ca0] hover:bg-[#d9a7a4] font-bold px-5 py-2 rounded transition duration-400 mr-3">
                        Login
                    </a>
                    <a href="{% url 'main:register' %}" class="text-center text-white bg-[#c78ca0] hover:bg-[#d9a7a4] font-bold px-5 py-2 rounded transition duration-400 mr-3">    
                        Register
                    </a>
                {% endif %}
            </div>
            <div class="md:hidden flex items-center">
                <button class="mobile-menu-button">
                    <svg class="w-6 h-6 text-black" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
                        <path d="M4 6h16M4 12h16M4 18h16"></path>
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <div class="mobile-menu hidden md:hidden px-4 w-full md:max-w-full">
        <div class="pt-2 pb-3 space-y-1 mx-auto">
            <a href="#Home" class="block text-black font-bold px-3 py-2 mb-2">
                Home
            </a>
            <a href="#Products" class="block text-black font-bold px-3 py-2 mb-2">
                Products
            </a>
            {% if user.is_authenticated %}
                <span class="block text-black px-3 py-2">
                    Welcome, {{ user.username }}
                </span>
                <a href="{% url 'main:logout' %}" class="block text-center text-white bg-[#c78ca0] hover:bg-[#d9a7a4] font-bold px-4 py-2 rounded transition duration-300">
                    Logout
                </a>
            {% else %}
                <a href="{% url 'main:login' %}" class="block text-center text-white bg-[#c78ca0] hover:bg-[#d9a7a4] font-bold px-4 py-2 rounded transition duration-300 mb-2">
                    Login
                </a>
                <a href="{% url 'main:register' %}" class="block text-center text-white bg-[#c78ca0] hover:bg-[#d9a7a4] font-bold px-4 py-2 rounded transition duration-300">
                    Register
                </a>
            {% endif %}
        </div>
    </div>
    <script>
        const btn = document.querySelector(".mobile-menu-button");
        const menu = document.querySelector(".mobile-menu");

        btn.addEventListener("click", () => {
            menu.classList.toggle("hidden");
        });
    </script>
</nav>